### ISSUE TITLE
@AndroidFindBy and @iOSFindBy for native app automation

### ISSUE THREAD

**Issue by email2vimalraj** [appium/java-client#184] opened 2015-04-15 09:23 UTC
As suggested in https://github.com/appium/java-client/pull/68#issuecomment-93260061:

We should have the annotations @AndroidFindBy and @iOSFindBy support for native apps also. Currently it supports only for the web view.

I would also suggest from my point of view to make AppiumDriver as interface instead of keeping it as abstract.

**Comment by TikhomirovSergey** [comment] 2015-04-15 10:33
Hi!
They are designed generally for native apps. Please provide the detailed report of the problem that you've found. Stacktraces, locators, code samples etc. What locators do you use? What java_client version/server version? Below examples that work against native app:

```java
@FindBy(css = "someBrowserCss") //this locator is used when here is browser (desktop or mobile) 
@iOSFindBy(uiAutomator = ".elements()[0]") //this locator is used when here is iOS native content 
@AndroidFindBy(className = "android.widget.TextView") //this locator is used when here is Android  
//native content 
public List<WebElement> androidOriOsTextViews; 

 
@AndroidFindBy(uiAutomator = "new UiSelector().resourceId(\"android:id/text1\")") 
public List<WebElement> androidUIAutomatorViews; 

@AndroidFindBy(uiAutomator = "new UiSelector().resourceId(\"android:id/text1\")") 
public List<MobileElement> mobileElementViews; //Also with Appium page object tools it is 
//possible to declare RemoteWebElement or any MobileElement subclass 

@FindBy(className = "android.widget.TextView") 
public List<MobileElement> mobiletextVieWs; 

@AndroidFindBy(uiAutomator = "new UiSelector().resourceId(\"android:id/text1\")") 
public List<RemoteWebElement> remoteElementViews; 

 
@AndroidFindBy(id = "android:id/text1") 
public WebElement textView; 
```

Full samples:
[Android 1](https://github.com/appium/sample-code/blob/master/sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/page_object/android/ApiDemosListViewScreenSimple.java)
[Android 2](https://github.com/appium/sample-code/blob/master/sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/page_object/android/ApiDemosListViewScreenChaided.java)
[Android 3](https://github.com/appium/sample-code/blob/master/sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/page_object/android/ApiDemosListViewScreenByAllPossible.java)
[iOS](https://github.com/appium/sample-code/blob/master/sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/page_object/ios/TestAppScreenSimple.java)

About interface. Actually it exists. [MobileDriver](https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/MobileDriver.java). There is [new extended version](https://github.com/TikhomirovSergey/java-client/blob/returning_of_mobileelement/src/main/java/io/appium/java_client/MobileDriver.java) that probably will be merged.

**Comment by Simon-Kaz** [comment] 2015-04-23 16:41
@TikhomirovSergey I'm having issues with the following annotation:

@iOSFindBy(accessibility = "Tracker")
    private MobileElement trackerButton;

When i use it, the following shows up in the console:

au.getElementsById('flightTrackerButton')
au.getElementsByName('flightTrackerButton')
au.getElementsByAccessibilityId('flightTrackerButton')


It looks like the annotation is not passing the selector?

**Comment by TikhomirovSergey** [comment] 2015-04-23 16:47
Hi @Simon-Kaz 
It is interesting. Is it browser test?

**Comment by Simon-Kaz** [comment] 2015-04-23 16:47
Native app.

**Comment by TikhomirovSergey** [comment] 2015-04-23 16:51
Ok. I will try to repaet this today. 
What java_client version you use? It will be nice if you provide capabilities that you use.

**Comment by Simon-Kaz** [comment] 2015-04-23 16:53
Sure, I'm getting the data that I have right now... Will edit this post in a minute.

**Comment by TikhomirovSergey** [comment] 2015-04-23 17:01
...and... I've forgotten to ask. Does this find the wrong element or throw the NoSuchElementException?

**Comment by Simon-Kaz** [comment] 2015-04-23 17:02
No such element exception, as there's no element with that name/id/label.

**Comment by Simon-Kaz** [comment] 2015-04-23 17:07
OK it works outside of my project, guess I'll have to do some digging and find out why the annotation is not working :(

**Comment by TikhomirovSergey** [comment] 2015-04-23 17:17
Can you define the path to your app like [this](https://github.com/appium/sample-code/blob/master/sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/UICatalogTest.java#L62) or [that](https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ios/IOSDriverTest.java#L55). Does it help?
Do you define the path to your app via Appium desktop UI. What server version do you use?

**Comment by TikhomirovSergey** [comment] 2015-04-23 17:28
If I'm right then it is possible that your problem is related to https://github.com/appium/appium/issues/4091. Given capabilities and capabilities that are defined in the server side via desktop UI are not merged. Then you have to define the path to app in Java code till it fixed.

Actually I use Appium UI infrequently :)

**Comment by TikhomirovSergey** [comment] 2015-04-23 21:30
@Simon-Kaz @email2vimalraj 

It seems I'm right. Please look below.

Here are settings:
![1](https://cloud.githubusercontent.com/assets/4927589/7307537/26a6c586-ea16-11e4-9c0d-645385007d1b.png)

The code:
![1](https://cloud.githubusercontent.com/assets/4927589/7307670/02b29f1e-ea17-11e4-809d-2fc86d959b6b.png)

The command 
```java
  ((IOSDriver) driver).getCapabilities()
```
returns 

![1](https://cloud.githubusercontent.com/assets/4927589/7307792/c71a7606-ea17-11e4-9436-ebbd7108bc53.png)

So Appium page object tools attempt to handle it the way like here is mobile or desktop browser. Because there is no  __FindBy__ and __iOS/AndroidFindBy__ are for apps it tries to locate the element using Id or name that supposed to be equal to field name. 

```java
org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: by id or name "iosButton"
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
System info: host: 'Mac-Admin.local', ip: '192.168.42.129', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_25'
```

It think the root cause has been described in referred issue. The workaround in previous message.

**Comment by Simon-Kaz** [comment] 2015-04-24 08:28
Sorry for late response - The reason I'm not specifying an app capability is because I have the app pre-installed with ideviceinstaller. I use bundleId and udid to run the tests.

**Comment by TikhomirovSergey** [comment] 2015-04-24 08:34
Ok. I everithing ok now? Can we close this issue?

**Comment by Simon-Kaz** [comment] 2015-04-24 08:51
I'd keep it open until I find a resolution, as it's still a problem for me. Once I find a solution, I'll update this ticket (for future reference if someone encounters the same issue) and close it then.

**Comment by TikhomirovSergey** [comment] 2015-04-24 08:59
Ok. I think the app should be calculated on the server-side and returned in capabilities (in your case). What do you think about this feature? If you find this cool and https://github.com/appium/appium/issues/4091 is not relevant please open a new issue here: https://github.com/appium/appium/issues

**Comment by Simon-Kaz** [comment] 2015-04-24 09:11
I just checked, and this is what's returned:

"platformVersion":"8.1.2",
"bundleId":"app's bundle id ",
"platformName":"iOS",
"udid":"udidNumber",
"deviceName":"iPhone 6",
"autoAcceptAlerts":true

Looks like it's not related to the issue you mentioned :( I'll try using app capability and see if that helps

**Comment by TikhomirovSergey** [comment] 2015-04-24 09:53
I know how to fix the app determination. Today I'll propose a pull-request.

**Comment by Simon-Kaz** [comment] 2015-04-24 10:04
Perfect, thank you!

**Comment by TikhomirovSergey** [comment] 2015-04-27 22:47
Hi @Simon-Kaz 
The fix is at reffered PR above. Please look at this. You could comment it and help me and @Jonahss

**Comment by Simon-Kaz** [comment] 2015-04-28 13:57
I see it's been merged, that's great, thanks! Anything else that you need me to do? I can try and reproduce the issue with latest build of Appium.

**Comment by TikhomirovSergey** [comment] 2015-04-28 15:22
@Simon-Kaz you can review this. You can clone master, build it locally and try to reproduce... If you want :)

**Comment by justintilson** [comment] 2015-06-30 20:07
Hey guys. I'm getting a similar issue as @Simon-Kaz. I tried versions 2.2.0 and 3.0.0 with the same result.

Here is a sample property from one of my page objects:

```java
@iOSFindBy(accessibility = "home_landing_my_favorites_count_label")
WebElement myFavoritesCountLabel;
```
and a screenshot from my debugger:

![unknown-locator](https://cloud.githubusercontent.com/assets/1480031/8440584/1b3c0b9c-1f41-11e5-9321-1bd2e513548e.png)

Instead of using the supplied accessibility identifier to locate elements, PageFactory.initElements is attempting to use the property name as the identifier.

**Closed** 2015-07-06 18:32 UTC

**Comment by tomb50** [comment] 2015-07-31 12:02
This issue looks to still persist even with the fixes introduced with v3.1.0 which has the above, I am running against Appium 1.4.8 (no GUI app).

@IOSFindBy(accessibility = "123)
public WebElement abc

Is still trying to find using the instance variable value and not "123".

Please let me know if any additional info is required.

**Comment by tomb50** [comment] 2015-07-31 12:19
Just to confirm, the CONTEXT is NATIVE_APP and Desired Capabilities are the same as previous posters, the App is specified.

**Comment by tomb50** [comment] 2015-07-31 12:52
Disregard my comments, I was an idiot and was passing the driver directly into PageFactory.initElements() rather than a new AppiumFieldDecorator.

**Comment by salmanchauhan** [comment] 2016-03-17 10:18
I am trying to use strategies 
@FindBy(css = "someBrowserCss")
@iOSFindBy(uiAutomator = ".elements()[0]") 
@AndroidFindBy(className = "android.widget.TextView")
and i am using 
PageFactory.initElements(new AppiumFieldDecorator(driver, DRIVER_WAIT, TimeUnit.SECONDS),this);

For iOS my script works fine but for android i am getting this exception.
**java.lang.IllegalArgumentException: @$Proxy9: one of [uiAutomator, accessibility, className, id,tagName, name, xpath, linkText, partialLinkText] should be filled at io.appium.java_client.pagefactory.bys.builder.AppiumByBuilder.getFilledValue(AppiumByBuilder.java:89)
	at **io.appium.java_client.pagefactory.bys.builder.AppiumByBuilder.getComplexMobileBy(AppiumByBuilder.java:112)
	at io.appium.java_client.pagefactory.bys.builder.AppiumByBuilder.createBy(AppiumByBuilder.java:136)
	at io.appium.java_client.pagefactory.DefaultElementByBuilder.buildMobileNativeBy(DefaultElementByBuilder.java:153)
	at io.appium.java_client.pagefactory.DefaultElementByBuilder.buildBy(DefaultElementByBuilder.java:189)
	at io.appium.java_client.pagefactory.AppiumElementLocatorFactory.createLocator(AppiumElementLocatorFactory.java:61)
	at io.appium.java_client.pagefactory.AppiumElementLocatorFactory.createLocator(AppiumElementLocatorFactory.java:46)
	at io.appium.java_client.pagefactory.AppiumElementLocatorFactory.createLocator(AppiumElementLocatorFactory.java:1)
	at org.openqa.selenium.support.pagefactory.DefaultFieldDecorator.decorate(DefaultFieldDecorator.java:56)
	at io.appium.java_client.pagefactory.AppiumFieldDecorator.decorate(AppiumFieldDecorator.java:155)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:113)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
	at com.testapp.pages.AbstractPage.loadPage(AbstractPage.java:80)
	at com.testapp.pages.indexpage.DashboardIndexPage.<init>(DashboardIndexPage.java:31)
	at com.testapp.Init.SetupInit.dashboardIndexPage(SetupInit.java:188)
	at com.testapp.pages.indexpage.PreferencesIndexPage.performSignOutFromDashboardPageIfUserEmailNot(PreferencesIndexPage.java:179)
	at com.testapp.verifications.ProfileTest.VerifyGeneralFeature_AvailableOptionsScenario(ProfileTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

**Comment by robintel** [comment] 2017-11-23 17:11
@tomb50 

Hello,

It is unclear to me how you fixed it. Can you give some more details?

Thanks,
Robin

**Comment by nttrazvan** [comment] 2017-11-24 11:15
Hello @tomb50 ,

Could you please provide a more detailed solution to this, I'm facing the same issue.

Razvan

**Comment by vikramvi** [comment] 2017-12-12 08:13
@robintel @nttrazvan can you please check https://github.com/appium/appium/issues/9780 and add your comments as well.

It's always better to create new issue than commenting on closed one.

**Comment by ppzzss** [comment] 2018-05-03 12:10
Below annotations work well in Appium 1.7.2

@iOSXCUITFindBy (xpath = "xxxx")
@AndroidFindBy (id = "bbbb")
public WebElement usernameTextField;

**Comment by ppzzss** [comment] 2018-05-03 12:11
with Java_client 5.0.4

**Comment by Amrkamel1** [comment] 2019-03-27 12:16
Any one knows how to define an **xpath** that contains specific **id** and **text** using @AndroidFindBy 

**this is the element  :**
driver.findElement(By.xpath("//android.widget.TextView[contains(@resource-id,'com.sec.android.app.music:id/tab_text') and @text='TRACKS']"))

**i tried to add it in that way :**

 @AndroidFindBy(xpath = "\"//android.widget.TextView[contains(@resource-id,'com.sec.android.app.music:id/tab_text') and @text='TRACKS']\"")
    private WebElement TrackList; 

**but didnt work  and shows me this message :**

org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: By.chained({By.xpath: "//android.widget.TextView[contains(@resource-id ='com.sec.android.app.music:id/tab_text') and @text='TRACKS']"})

**Comment by adityabhargav** [comment] 2019-08-14 05:53
> @TikhomirovSergey I'm having issues with the following annotation:
> 
> @iOSFindBy(accessibility = "Tracker")
> private MobileElement trackerButton;
> 
> When i use it, the following shows up in the the appium logs:
> 
> au.getElementsById('trackerButton')
> au.getElementsByName('trackerButton')
> au.getElementsByAccessibilityId('trackerButton')
> 
> It looks like the annotation is not passing the selector?
> 
> EDIT: I've just tried changing the "accessibility" to "name", and it's the same.

-----------------------
Answer :- 

> @iOSFindBy(accessibility = "Tracker")
> private MobileElement trackerButton;

trackerButton - is similar to "driver.findElement(By.Id("Tracker"))"

need to give like

trackerButton.Click();

Note:- trackerButton is not alone a mobile element , it carries property of "driver.findElement(By.Id("Tracker"))".
