### ISSUE TITLE
issue in java client

### ISSUE THREAD

**Issue by danubiapaiva** [appium/java-client#561] opened 2017-01-29 11:52 UTC
Appium
Windows 10

org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{app=D:\Automacao\Banestes.apk, platformName=Android, deviceName=Android Emulator}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'DESKTOP-T3J392Q', ip: '192.168.105.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:69)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:141)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:83)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:72)
	at pagamento.Boleto_bancario.testeLogin(Boleto_bancario.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by mykola-mokhnach** [comment] 2017-01-29 14:29
Please use the "avd" capability if you want to set the name of existing simulator (not a real device). Also, make sure the provided simulator name exists in

```
android list avd
```

output. 

http://appium.io/slate/en/master/?java#android-only

**Comment by danubiapaiva** [comment] 2017-01-29 19:50
I use genymotion simulator, I have problens only windows 10, in windows 7 is ok.

**Comment by mykola-mokhnach** [comment] 2017-01-29 19:51
What do you see in Appium log?

**Comment by danubiapaiva** [comment] 2017-01-29 19:56
> Killed Node Server.
> Appium server process ended
> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --platform-name Android --platform-version 23 --automation-name Appium --log-no-color
> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"23","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/status/session {"capabilities":{"desiredCapabilities":{"app":"D:\\Automacao\\Banestes.apk","platformName":"Android","deviceName":"Android Emulator"},"requiredCapabilities":{}},"desiredCapabilities":{"app":"D:\\Automacao\\Banestes.apk","platformName":"Android","deviceName":"Android Emulator"},"requiredCapabilities":{}}
> info: [debug] Responding to client that we did not find a valid resource
> info: <-- POST /wd/hub/status/session 404 12.400 ms - 47 
> info: --> POST /wd/hub/status/session {"desiredCapabilities":{"app":"D:\\Automacao\\Banestes.apk","platformName":"Android","deviceName":"Android Emulator"},"requiredCapabilities":{}}
> info: [debug] Responding to client that we did not find a valid resource
> info: <-- POST /wd/hub/status/session 404 2.503 ms - 47 
> info: --> POST /wd/hub/status/session {"capabilities":{"desiredCapabilities":{"app":"D:\\Automacao\\Banestes.apk","platformName":"Android","deviceName":"Android Emulator"},"requiredCapabilities":{}}}
> info: [debug] Responding to client that we did not find a valid resource
> info: <-- POST /wd/hub/status/session 404 0.901 ms - 47

**Comment by mykola-mokhnach** [comment] 2017-01-29 20:00
Is it reproducible with the most recent Appium (1.6.3) and java_client (4.1.2) version?

**Comment by danubiapaiva** [comment] 2017-01-29 20:13
I try with java_client 4.1.2, but now is java_client 5.0.0-beta and appium 1.4.16.1, I made the update appium and it is this version

**Comment by mykola-mokhnach** [comment] 2017-01-29 20:15
beta might be unstable - that is why it is beta. Regarding Appium, you can to install the most recent version with Node Packages Manager (npm). Standalone .exe UI client is not supported anymore.

**Comment by danubiapaiva** [comment] 2017-01-29 20:46
Install with npm and altered java-client4.1.2, log appium:

> info: --> POST /wd/hub/status/session {"capabilities":{"desiredCapabilities":{"app":"D:\\Automacao\\Banestes.apk","platformName":"Android","deviceName":"Android Emulator"},"requiredCapabilities":{}},"desiredCapabilities":{"app":"D:\\Automacao\\Banestes.apk","platformName":"Android","deviceName":"Android Emulator"},"requiredCapabilities":{}}
> info: [debug] Responding to client that we did not find a valid resource
> info: <-- POST /wd/hub/status/session 404 0.909 ms - 47 
> info: --> POST /wd/hub/status/session {"desiredCapabilities":{"app":"D:\\Automacao\\Banestes.apk","platformName":"Android","deviceName":"Android Emulator"},"requiredCapabilities":{}}
> info: [debug] Responding to client that we did not find a valid resource
> info: <-- POST /wd/hub/status/session 404 1.640 ms - 47 
> info: --> POST /wd/hub/status/session {"capabilities":{"desiredCapabilities":{"app":"D:\\Automacao\\Banestes.apk","platformName":"Android","deviceName":"Android Emulator"},"requiredCapabilities":{}}}
> info: [debug] Responding to client that we did not find a valid resource
> info: <-- POST /wd/hub/status/session 404 2.072 ms - 47

**Comment by mykola-mokhnach** [comment] 2017-01-29 20:50
This does not look like Appium has been updated. Are you sure you see 1.6.3 version in the log?

**Comment by danubiapaiva** [comment] 2017-01-29 20:59
I performad "npm install appium@1.6.3" but is show > Checking if an update is available

> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)


Have other command?

**Comment by mykola-mokhnach** [comment] 2017-01-29 21:01
Seems like the old version is still running. Make sure it is killed and the new one is started. Please use Appium forum in case you have more howto questions.

**Comment by danubiapaiva** [comment] 2017-01-29 21:45
Tks, I starting the version 1.6.3, The error has changed, I will put there. Thank you

**Comment by TikhomirovSergey** [comment] 2017-01-30 08:36
@danubiapaiva @mykola-mokhnach 
Hi guys. So is the issue related to invalid installation? May I close it?

Also. The version of server 1.6.3 or higher is recommended for the client 5.x

**Comment by mykola-mokhnach** [comment] 2017-01-30 08:43
@TikhomirovSergey yes, please close it as duplicate of https://github.com/appium/appium/issues/7771

**Closed** 2017-01-30 09:48 UTC
