### ISSUE TITLE
[.getAttribute("value")] always returns null, iOS

### ISSUE THREAD

**Issue by wzlsquall** [appium/java-client#1289] opened 2020-01-06 03:17 UTC
## Description

[.getAttribute("value")] always returns null in my test program.

## Environment

* Java client build version or git revision if you use some snapshot: 7.2.0
* Appium server version or git revision if you use some snapshot: 
* Desktop OS/version used to run Appium if necessary: macOS Mojave 10.14.6
* Mobile platform/version under test: IOS 12.4.3
* Real device or emulator/simulator: iPhone 6

## Details

It can get value attribute in inspector  when I using appium deskop to test app on iPhone, but [.getAttribute("value")] always returns null in my test program.

Target element can be found by accessibility id.

**Comment by KazuCocoa** [comment] 2020-01-06 03:27
If you're using Xcode 11, it is duplicate of https://github.com/appium/appium/issues/13288

**Comment by wzlsquall** [comment] 2020-01-06 03:56
> If you're using Xcode 11, it is duplicate of [appium/appium#13288](https://github.com/appium/appium/issues/13288)

So, there is no way that can help me to get the actual value, isn't it.

**Comment by KazuCocoa** [comment] 2020-01-06 04:45
Yes.
Or you can use Xcode 10.x for iOS 12

**Comment by wzlsquall** [comment] 2020-01-06 06:05
> Yes.
> Or you can use Xcode 10.x for iOS 12

Thanks

**Closed** 2020-01-07 03:01 UTC

**Comment by Lyuxy** [comment] 2020-01-15 02:06
> Yes.
> Or you can use Xcode 10.x for iOS 12

update to iOS 13 can fix this issue?

**Comment by KazuCocoa** [comment] 2020-01-19 03:45
It depends on your situation, as far as I know.
XCTest in Xcode 11.x does not work well on iOS 12, while Xcode 10..x works on iOS 12.
Xcode 11 works well only on iOS 13. Not sure newer Xcode versions, but Xcode 11, 11.1 and 11.2 had such issues.

Basically, the returned values depend on XCTest maintained by Apple.

**Comment by ebonom-mfam** [comment] 2022-01-28 13:35
Hey guys, I am experiencing this issue with t xcode 13.1. Does anyone know a solution for this xcode version? @KazuCocoa

**Comment by KazuCocoa** [comment] 2022-01-28 17:34
I don't know if Apple fixed this issue. If still newer xcode has this issue, still they haven't fixed this yet.
