### ISSUE TITLE
java-client's NewSessionPayload.class conflict with selenium's NewSessionPayload.class

### ISSUE THREAD

**Issue by Tenit2012** [appium/java-client#875] opened 2018-04-26 10:33 UTC
OS: Windows 10
Selenium Version: 3.9.1
Browser: Firefox
Browser Version: 59.0.2 (64-bit) 

## Expected Behavior
- When start Firefox driver will call class NewSessionPageload.java of selenium instead call NewSessionPageload.java of java-client.
## Actual Behavior
- When start Firefox driver  called class NewSessionPageload.java of java-client  instead call NewSessionPageload.java of selenium.
- Error message.
**Exception in thread "main" org.openqa.selenium.InvalidArgumentException: firefox_profile is not the name of a known capability or extension capability**

## Steps to reproduce 

- Please run source code to reproduce :
```

   public class FirefoxTest {
	public static void main(String[] args) {
         // declaration and instantiation of objects/variables
        System.setProperty("webdriver.gecko.driver", "/path/to/geckodriver_win64.exe");          
        FirefoxProfile ffprofile = new FirefoxProfile();
    	FirefoxOptions firefoxOptions = new FirefoxOptions();
    	firefoxOptions.setProfile(ffprofile);
	WebDriver driver = new FirefoxDriver(firefoxOptions);
        String baseUrl = "http://demo.guru99.com/test/newtours/";
        String expectedTitle = "Welcome: Mercury Tours";
        String actualTitle = "";
        driver.get(baseUrl);
        // get the actual value of the title
        actualTitle = driver.getTitle();
        /*
         * compare the actual title of the page with the expected one and print
         * the result as "Passed" or "Failed"
         */
        if (actualTitle.contentEquals(expectedTitle)){
            System.out.println("Test Passed!");
        } else {
            System.out.println("Test Failed");
        }     
        //close Fire fox
         driver.close();
           }
       }
```
------------------------------------------pom.xml file------------------------------------------------------

          <?xml version="1.0" encoding="UTF-8"?>
	<project xmlns="http://maven.apache.org/POM/4.0.0" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>DemoFirefoxDriver</groupId>
	<artifactId>DemoFirefoxDriver</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<properties>
		<selenium.webdriver.version>3.9.1</selenium.webdriver.version>
	</properties>
	<build>
		<plugins>
			<plugin>
				
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>6.0.0-BETA3</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>${selenium.webdriver.version}</version>
			<exclusions>
				<exclusion> 
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpclient</artifactId>
				</exclusion>
				<exclusion>
					<groupId>xalan</groupId>
					<artifactId>xalan</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
                <dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>${selenium.webdriver.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.seleniumhq.selenium</groupId>
					<artifactId>selenium-firefox-driver</artifactId>
				</exclusion>
				<exclusion>
					<groupId>xalan</groupId>
					<artifactId>xalan</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-firefox-driver</artifactId>
			<version>${selenium.webdriver.version}</version>
		</dependency>

		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-ie-driver</artifactId>
			<version>${selenium.webdriver.version}</version>
		</dependency>

		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-chrome-driver</artifactId>
			<version>${selenium.webdriver.version}</version>
		</dependency>

		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-edge-driver</artifactId>
			<version>${selenium.webdriver.version}</version>
		</dependency>

		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-safari-driver</artifactId>
			<version>${selenium.webdriver.version}</version>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>24.0-jre</version>
		</dependency>
	</dependencies>
</project>

-------------------------------------------------------------------------------------------------------------------
-  This is a bug of java-client?
- Do Anyone have the workaround for this issue? Please advice me. Thank in advance!

**Comment by Trucnt** [comment] 2018-04-27 07:10
Hi @SrinivasanTarget , @TikhomirovSergey ,
I have same this problem. Can you look into it? 
Please let me know if you've any update/question. Thanks so much.

**Comment by Trucnt** [comment] 2018-04-27 08:51
Anything works fine until the NewSessionPayload class is created in java-client at version 6.0.0-BETA3.

Here is a screenshot of java-client's NewSessionPayload class is called:
![newsessionpayload collisions](https://user-images.githubusercontent.com/11989361/39353727-bcef952a-4a32-11e8-8113-995572c01eaa.png)

**Comment by TikhomirovSergey** [comment] 2018-04-27 20:11
@Trucnt 
Hello! Could remove all dependencies on Selenium? I am suspecting the conflict of dependencies on selenium. I am seing that your project is depending on Selenium v3.9.1. Appium java client v6.0.0-BETA3 depends on 3.10. Also you can update your project to v6.0.0-BETA4

**Comment by TikhomirovSergey** [comment] 2018-04-28 07:16
@Tenit2012 The reply above is for you too.

**Comment by Tenit2012** [comment] 2018-05-02 07:35
Hi @TikhomirovSergey 
Perhaps you have misunderstood my problem.

My problem is when I run with **Firefox driver**, ProtocalHandShake.java class of library selenium called **NewsessionPayload.java** class of java-client library instead call **NewsessionPayload.java** class of selenium library.

I want to run with **Firefox driver**, ProtocalHandShake.java class will call **NewsessionPayload.java** of selenium library. Because both selenium and the Appium java-client contains **org.openqa.selenium.remote.NewsessionPayload.java.**

Did you reproduce on my issue? 
Please read my issue carefully and let me know if you've any question/concern. Tks.

**Comment by Trucnt** [comment] 2018-05-03 02:14
Is it indeed an Appium java client issue, @TikhomirovSergey ?

**Comment by TikhomirovSergey** [comment] 2018-05-07 19:28
Guys. I am investigating

**Comment by TikhomirovSergey** [comment] 2018-05-07 22:53
Guys @Trucnt @Tenit2012 
I can't reproduce the problem. 

[The sample](https://gist.github.com/TikhomirovSergey/af5e502d7d82b553c3302d6f8b02187f)

[The console ouput](https://gist.github.com/TikhomirovSergey/0daf4a85c072da8354b1cf430fbf2bc2)

![image](https://user-images.githubusercontent.com/4927589/39728591-6ed774ee-5260-11e8-93b2-f5e0a2e83d94.png)

It is normal now that **NewsessionPayload** from appium is used instead of the same class from selenium. It was the necessary step and we hope the situation will be changed. Also the appium lib has all dependencies from selenium. 

Could you remove the dependency on **selenium java** and add such exclusion to **selenium-server** dependency? What the result?

**Comment by Trucnt** [comment] 2018-05-08 03:14
Hey @TikhomirovSergey ,

As your suggestion, I have removed both selenium-java and selenium-server but this issue still happens.

To reproduce this problem, You must create FirefoxDriver with FirefoxOptions and FirefoxProfile is set into FirefoxOptions.

Further detail, please see screenshot below:

![appium-java-client-issue](https://user-images.githubusercontent.com/11989361/39735042-f8e5b6b2-52a3-11e8-8ed2-bf4c41c8a603.png)

Please let me know if any update. Thanks in advance.

**Comment by TikhomirovSergey** [comment] 2018-05-08 20:47
Ok. Trying to work it out

**Comment by TikhomirovSergey** [comment] 2018-05-08 21:31
Yes. I could reproduce this error. It seems something was broken because we did not test it on desktop browser.

**Comment by TikhomirovSergey** [comment] 2018-05-22 13:39
The fix was merged. It is going to be published soon.

**Closed by TikhomirovSergey** 2018-05-22 13:39 UTC
Labels: bug
