### ISSUE TITLE
Cannot swipe from bottom to top on ios 

### ISSUE THREAD

**Issue by shay777** [appium/java-client#419] opened 2016-06-19 07:42 UTC
I would like to set the wifi status on ios and in order to do that, I need to to swipe up from the bottom the Control Center.

            dimension = driverWrapper.getIosDriver().manage().window().getSize();
            int middleX = dimension.getWidth() / 2;
            int y = dimension.getHeight();
            driverWrapper.getIosDriver().swipe(middleX,y - 10 ,middleX,150,600);
//            action = new TouchAction(driverWrapper.getIosDriver());
//            action.press(middleX, y - 10 ).waitAction(100)
//                    .moveTo(middleX, y / 2).release().perform();

I used both of the codes and nothing works. Before I upgraded java client to 4.0.0 and appium to 1.5.2 it worked correctly.

## Environment

* java client build version or git revision if you use some shapshot: 4.0.0
* Appium server version or git revision if you use some shapshot: 1.5.2
* Desktop OS/version used to run Appium if necessary: mac os
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: ios 9 and above
* Real device or emulator/simulator: real device

## Ecxeption stacktraces

I get an error of:
Error: VerboseError: point is not within the bounds of the screen

## Link to Appium logs

[debug] [UIAuto] Socket data received (49 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"width":320,"height":568}}
[MJSONWP] Responding to client with driver.getWindowSize() result: {"width":320,"height":568}
[HTTP] <-- GET /wd/hub/session/31411e39-f408-418f-b9b8-e28b80ba1b35/window/current/size 200 1071 ms - 98 
[HTTP] --> POST /wd/hub/session/31411e39-f408-418f-b9b8-e28b80ba1b35/touch/perform {"actions":[{"action":"press","options":{"x":160,"y":558}},{"action":"wait","options":{"ms":100}},{"action":"moveTo","options":{"x":160,"y":284}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":160,"y":558}},{"action":"wait","options":{"ms":100}},{"action":"moveTo","options":{"x":160,"y":284}},{"action":"...
[debug] [iOS] Executing iOS command 'performTouch'
[debug] [UIAuto] Sending command to instruments: target.touch([{"touch":[{"x":160,"y":558}],"time":0.2},{"touch":[{"x":160,"y":558}],"time":0.30000000000000004},{"touch":[{"x":320,"y":842}],"time":0.5}])

[debug] [Instruments] [INST] 2016-06-19 07:39:13 +0000 Debug: Got new command 6 from instruments: target.touch([{"touch":[{"x":160,"y":558}],"time":0.2},{"touch":[{"x":160,"y":558}],"time":0.30000000000000004},{"touch":[{"x":320,"y":842}],"time":0.5}])

[debug] [Instruments] [INST] 2016-06-19 07:39:13 +0000 Debug: evaluating target.touch([{"touch":[{"x":160,"y":558}],"time":0.2},{"touch":[{"x":160,"y":558}],"time":0.30000000000000004},{"touch":[{"x":320,"y":842}],"time":0.5}])

[debug] [Instruments] [INST] 2016-06-19 07:39:13 +0000 Debug: target.touch(__NSCFArray)

[debug] [Instruments] [INST] 2016-06-19 07:39:13 +0000 Debug: point is not within the bounds of the screen

**Comment by shay777** [comment] 2016-06-20 07:13
any answer regarding this?
thanks

**Comment by TikhomirovSergey** [comment] 2016-06-20 19:43
@shay777 
Hi. Sorry for the late response.

About the code sample below:
>// action = new TouchAction(driverWrapper.getIosDriver());
>// action.press(middleX, y - 10 ).waitAction(100)
>// .moveTo(middleX, y / 2).release().perform();

It is because of the change on the server side:
https://medium.com/@scottdixon/appium-touch-examples-w-nodejs-ios-wd-ee2b9956aab1

So now the moving uses **relative** values instead of **absolute**.

About the swiping. There was an issue which is fixed now
https://github.com/appium/java-client/issues/350

It is covered with tests and it seems everything should be fine.

Which the last server version you code worked fine?
Could you provide the full server log?

Also

Why do try to change connection that way? There is another way to do the same:
https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/android/AndroidConnectionTest.java

**Comment by shay777** [comment] 2016-06-21 11:29
Thanks for your response.
What do you mean by using relative values? 
Is this what you meant?
            dimension = driverWrapper.getIosDriver().manage().window().getSize();
            int middleX = dimension.getWidth() / 2;
            int y = dimension.getHeight();
             action = new TouchAction(driverWrapper.getDriver());
             action.press(middleX, (int) (y - (y*0.0015))).waitAction(100)
             .moveTo(middleX, (int) (0.5*y)).release().perform();
I upgraded the java-client to 4.0.0 and the appium version to 1.5.2. Before that I used appium version 1.4.8 and it worked correctly.
the full logs are:
[logs.txt](https://github.com/appium/java-client/files/325423/logs.txt)

When I use this:
            dimension = driverWrapper.getIosDriver().manage().window().getSize();
            int middleX = dimension.getWidth() / 2;
            int y = dimension.getHeight();
            driverWrapper.getDriver().swipe(middleX, (int) (y - (y*0.0015)),middleX, (int) (0.5*y),600);
i get no error. The swipe is skipped. The driver not performs the swipes at all.
This connection method seems to be only in android and not in ios. I use ios.

Thanks

**Comment by shay777** [comment] 2016-06-22 09:31
I tried many values for x and y and nothing works.
driverWrapper.getDriver().swipe((int) (0.99*x), (int) (0.99*y), (int) (0.5*x), (int) (0.5*y), 1000);
This one press on a button if there is any but never swipes if there is none

**Comment by SrinivasanTarget** [comment] 2016-07-06 19:05
Hey @shay777 

This is an expected behaviour going forward.Since we use relative co.ordinates in latest architecture this is the behaviour we expect.It worked previously because iOS co ordinates were absolute, so users were able to use a workaround to swipe up on iOS device to turn ON?OFF wifi. But as latest arch is not absolute this is an expected behaviour. We moved to relative as per the webdriver specs and it was actually broken in 1.4 arch.

Sad to say that we can't use the workaround going forward.Feel free to raise your questions if any.

I'm closing this for now as this is an expected behaviour.

**Closed by SrinivasanTarget** 2016-07-06 19:05 UTC
Labels: Needs investigation

**Comment by 03623170** [comment] 2016-08-12 12:08
I have the same problem on a real device iPhone 6s plus. I can only swipe from above but from the bottom, it doesn't work for me. I did tried the above workaround with the released java-client 4.0.0. and v1.5.3. On the bottom of our app is a NavigationBar with my code it just tap on the button at the given position and nothing more happens:

```
Dimension d = driver.manage().window().getSize();

        int height = d.getHeight();
        int endHeight = height /2;
        int width = d.getWidth();
        int endWidth = width /2;
        driver.swipe(endWidth,height,endWidth,endHeight,2000);
```
I also tried the workaround with TouchAction with same output. What did I do wrong?

**Comment by shay777** [comment] 2016-08-14 08:51
You did nothing wrong. It seems to be the expected behavior for some reason.
I gave up after a lot of search and workarounds.
I switched back to an older version of appium (1.4.16) and now it works perfectly.

**Comment by shay777** [comment] 2016-09-29 12:29
I upgraded appium to 1.6.0 -beta1. Because of that I cannot swipe from bottom to top in order to reach the wifi. I understand that it is the expected behavior but any way I can swipe in order to see the wifi?

**Comment by dnphung** [comment] 2016-09-29 13:40
I haven't tried it yet for the control-menu but you can try this code and change .moveTo() with the max height size coordinate of the screen.
`Dimension screenSize = driver.manage().window().getSize();

		int screenHeight = (screenSize.getHeight() / 2) + 100;
		int screenWidth = screenSize.getWidth() / 2;

		TouchAction ta = new TouchAction(driver);
		MultiTouchAction ma = new MultiTouchAction(driver);

		ta.press(screenWidth, screenHeight)
				.waitAction(1000)
				.moveTo(screenWidth, 100)
				.release();
		ma.add(ta).perform();`

This works for me for standard swipe up on screen

**Comment by shay777** [comment] 2016-10-02 07:33
I have tried it with many variations but it doesn't work.
Not sure why this is happening.

**Comment by shay777** [comment] 2016-10-02 07:41
@TikhomirovSergey @SrinivasanTarget  Maybe someone from the development team can provide a solution regarding how to swipe from bottom to top in ios and basically reveal the control center?
thanks

**Comment by SrinivasanTarget** [comment] 2016-10-02 16:28
@shay777 @dnphung Can you please try this? 

```
public static void pullToWifiOffline() {
		int height = driver.findElementByClassName("UIAWindow").getSize().getHeight();
		int width = driver.findElementByClassName("UIAWindow").getSize().getWidth();
		new TouchAction((MobileDriver) driver).press(width / 2, height).waitAction(1000).moveTo(width / 2, height - 200)
				.release().perform();
		MobileElement Airplane = (MobileElement) method.getElementById("Wi-Fi");
		Airplane.click();
		new TouchAction((MobileDriver) driver).tap(width / 2, 50).perform();
	}
```

**Comment by shay777** [comment] 2016-10-05 07:24
@SrinivasanTarget Thanks for your reply.
I am still not able to reveal the control center. The swipe is not working in this appium version.
This is the link for the gist. Maybe you can see something from it: https://gist.github.com/shay777/36ba2f8192913a90dca24a77a7cbee94
I am not sure I totally understand what you mean by legacy driver. I am working with mac if it's related.

**Comment by mykola-mokhnach** [comment] 2016-10-05 07:35
Control center can be also revealed by triple tap. You can try it as a workaround

**Comment by shay777** [comment] 2016-10-05 08:27
I tap 3 times on the home button but I get a screen where I can see all the open apps. It is not the control center. I am working with iphone 6 plus.

**Comment by mykola-mokhnach** [comment] 2016-10-05 08:34
not exactly,  - you need to simulate touch with three fingers.

**Comment by shay777** [comment] 2016-10-05 09:18
I am not sure I understand. You mean that I should simulate a touch action on the bottom of the screen with 3 fingers? When I do it manually nothing happens. Can you elaborate what exactly do you mean?

**Comment by mykola-mokhnach** [comment] 2016-10-05 09:22
I mean this: https://support.apple.com/en-us/HT202364
You can swipe from the bottom to the top at any point with three fingers to reveal Control Center

**Comment by shay777** [comment] 2016-10-05 11:16
I tried to perform a multi touch but nothing happens. A swipe from the bottom doesn't work. I can swipe from top, from the middle, to the sides... but swipe from bottom to top doesn't work. 
On previous versions of appium it worked correctly.

**Comment by xueying-tan** [comment] 2016-11-10 07:32
@shay777
I had the same issue, swiping from the top to the bottom didn't work , but swiping from the bottom to the top worked.
I tried  several times to swipe with my finger,  and found if I swiped slowly , it tend to failed to drag Control Center out , But if i swipe fast, I was able to drag Control Center out .

first I guess it is high duration value  that cause that issue.
and then i change swipe() to flick(), it worked.

the difference  between swipe() and flick() is that swipe has an extra step wait(ms=duration), following .press(x=start_x, y=start_y), which flick() hasn't.

I also tried to set the duration of swipe() to 0, which didn't work either.

It looks like that it was the wait() that cause the issue.

**Comment by estellemasso** [comment] 2016-11-16 20:39
@xueying-tan Please can you paste your code here. When I use flick() I get the error " Support for gestures other than Tap is not yet implemented. Please contact an Appium dev"
Thanks for helping. I am using python client.

**Comment by PrabhatPandey** [comment] 2017-04-24 11:53
Apparently in java-client-beta6 This bottom to top swipe issue is resolved. I am using 1.6.3 Appium , Xcode is 8. 

Putting the same code which work in iPhone-5s-10.2 

public static void SwitchWifiBar(AppiumDriver driver) {
        final int height = driver.findElementByClassName("UIAWindow").getSize().getHeight();
        final int width = driver.findElementByClassName("UIAWindow").getSize().getWidth();
        System.out.println("height"+height);
        System.out.println("width"+width);
        driver.swipe(width-100, height-5, width-100,0, 100);
        driver.findElementByAccessibilityId("Wi-Fi").click();
    }
