### ISSUE TITLE
PageObjects gets elements API instead of element API

### ISSUE THREAD

**Issue by saikrishna321** [appium/java-client#549] opened 2016-12-30 07:56 UTC
@TikhomirovSergey need help on this

Works fine 

```
@HowToUseLocators(androidAutomation = CHAIN)
    @AndroidFindBySet({
            @AndroidFindBy(xpath = "(.//*[@resource-id='org.wordpress.android:id/note_content_container'])[position()=2]"),
            @AndroidFindBy(uiAutomator = "new UiSelector().resourceId(\"org.wordpress.android:id/note_subject\")")
    }) //gets the third text from the note_subject view
```

Does not work

```
@HowToUseLocators(androidAutomation = CHAIN)
    @AndroidFindBySet({
            @AndroidFindBy(uiAutomator = "new UiSelector().resourceId(\"org.wordpress.android:id/note_content_container\").enabled(true).instance(2)"),
            @AndroidFindBy(uiAutomator = "new UiSelector().resourceId(\"org.wordpress.android:id/note_subject\")")
    }) //return the first text from the view 
``` 
https://gist.github.com/anonymous/d4440cab5e3213f9084498471201cd84

The above works fine, when we cast AndroidDriver

```
((AndroidDriver) driver).findElementByAndroidUIAutomator("new UiSelector().resourceId(\"org.wordpress.android:id/note_subject\").enabled(true).instance(2)").getText()
```

https://gist.github.com/anonymous/3b1fcc5761c370a1025d52c42b60b9fd

**Comment by TikhomirovSergey** [comment] 2016-12-30 09:02
@saikrishna321 
Please remove `@AndroidFindBySet` and check the result and use only AndroidFindBy :)

**Comment by saikrishna321** [comment] 2016-12-30 09:04
@TikhomirovSergey giving it a try now.. What does @AndroidFindBySet do ?

**Comment by TikhomirovSergey** [comment] 2016-12-30 09:05
It makes AndroidFindBy repeatable. 
http://docs.oracle.com/javase/tutorial/java/annotations/repeating.html

**Comment by saikrishna321** [comment] 2016-12-30 09:07
@TikhomirovSergey still the same, it just gets the default first locator's text value

**Comment by saikrishna321** [comment] 2016-12-30 09:08
https://gist.github.com/anonymous/cc08201899d52d47322604d3954817a3

**Comment by TikhomirovSergey** [comment] 2016-12-30 09:10
@saikrishna321 
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/pagefactory/AndroidFindBy.java#L34

Also if it is the chain by default you may not define
`@HowToUseLocators(androidAutomation = CHAIN)`

Please take a look at the [updated WIKI chapter](https://github.com/appium/java-client/blob/master/docs/Page-objects.md#also-it-is-possible-to-define-chained-or-any-possible-locators)

**Comment by TikhomirovSergey** [comment] 2016-12-30 09:15
@saikrishna321 
What happens when you try to 
```java
 driver.findElementByAndroidUIAutomator("new UiSelector().resourceId(\"org.wordpress.android:id/note_subject\").enabled(true).instance(2)").findElementByAndroidUIAutomator("new UiSelector().resourceId(\"org.wordpress.android:id/note_subject\")")
```
?

**Comment by saikrishna321** [comment] 2016-12-30 09:17
```
 @AndroidFindBy(uiAutomator = "new UiSelector().resourceId(\"org.wordpress.android:id/note_content_container\").enabled(true).instance(2)"),
            @AndroidFindBy(uiAutomator = "new UiSelector().resourceId(\"org.wordpress.android:id/note_subject\")")

public MobileElement getNotification;
```
With this as well the logs are same.

Here it picks the command with instance(3) https://gist.github.com/anonymous/cc08201899d52d47322604d3954817a3#file-updated-gist-with-androidfindby-L1132

and still looks for all elements 
https://gist.github.com/anonymous/cc08201899d52d47322604d3954817a3#file-updated-gist-with-androidfindby-L1148-L1161

> driver.findElementByAndroidUIAutomator("new UiSelector().resourceId(\"org.wordpress.android:id/note_subject\").enabled(true).instance(2)").findElementByAndroidUIAutomator("new UiSelector().resourceId(\"org.wordpress.android:id/note_subject\")")

It gives the Text at the Third view which is expected :)

**Comment by TikhomirovSergey** [comment] 2016-12-30 09:22
So does this code works well
```java
 driver.findElementByAndroidUIAutomator("new UiSelector().resourceId(\"org.wordpress.android:id/note_subject\").enabled(true).instance(2)")
.findElementByAndroidUIAutomator("new UiSelector().resourceId(\"org.wordpress.android:id/note_subject\")")
```
?
Ok. Has the same happened before (v<5.0.0-BETAx)? If there is a client bug then it may be the old problem that should be fixed

**Comment by saikrishna321** [comment] 2016-12-30 09:25
@TikhomirovSergey  
This works 

```
((AndroidDriver) driver).findElementByAndroidUIAutomator("new UiSelector().resourceId(\"org.wordpress.android:id/note_content_container\").enabled(true).instance(2)").
                findElement(MobileBy.AndroidUIAutomator("new UiSelector().resourceId(\"org.wordpress.android:id/note_subject\")")).getText();
```

Yah, i just tried with 4.1.2 and its the same. Chaining with unique ID's works, but with uiAutomation does not. Looks like we need to fix

**Comment by TikhomirovSergey** [comment] 2016-12-30 09:27
Yep. I will try to search for the root cause on the 1 Jan. For now please use xpath instead.

**Comment by saikrishna321** [comment] 2016-12-30 09:29
Cheers, this is required for the appium workshop(http://thoughtworks-bangalore.github.io/vodQA-Shots/) so wait for the fix

**Comment by TikhomirovSergey** [comment] 2016-12-30 09:39
@saikrishna321 
... and for your case it is enough 
```java
@AndroidFindBy(xpath = "(.//*[@resource-id='org.wordpress.android:id/note_content_container'])[position()=2]"),
@AndroidFindBy(uiAutomator = "new UiSelector().resourceId(\"org.wordpress.android:id/note_subject\")")
MobileElement element;
```

**Comment by saikrishna321** [comment] 2016-12-30 09:50
@TikhomirovSergey its calling elements instead of element api, can you please help in pointing where we call this api

https://gist.github.com/anonymous/cc08201899d52d47322604d3954817a3#file-updated-gist-with-androidfindby-L1132

**Comment by TikhomirovSergey** [comment] 2016-12-30 09:58
yes. 
It is here 
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/pagefactory/AppiumElementLocator.java#L157

I really think that root cause is here. But I can check it only tomorrow or on the 1 Jan.

**Comment by saikrishna321** [comment] 2016-12-30 09:59
myself and @SrinivasanTarget are looking at it, if we break through will send a PR

**Comment by TikhomirovSergey** [comment] 2016-12-30 09:59
@saikrishna321 
There were few reasons why it was designed that way. But I think it is outdated implementation for now.

**Comment by TikhomirovSergey** [comment] 2016-12-30 10:05
@saikrishna321 
>myself and @SrinivasanTarget are looking at it, if we break through will send a PR
Ok. 
But please keep it in mind that it should be NowSuchElementException-safe till waiting time is expired. 
Also please take a look at these classes from Selenium:
[ByAll](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/pagefactory/ByAll.java)
[ByChained](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/pagefactory/ByChained.java)

**Closed** 2017-01-02 21:54 UTC
Labels: bug, Needs investigation
