### ISSUE TITLE
Getting java.lang.NoClassDefFoundError: org/openqa/selenium/HasInputDevices while running Appium project

### ISSUE THREAD

**Issue by sjenasears** [appium/java-client#590] opened 2017-03-06 15:53 UTC
Java.lang.NoClassDefFoundError: org/openqa/selenium/HasInputDevices
getting this error while running appium script below in eclipse

@Before
public void setUp() throws Exception {

	
	DesiredCapabilities capabilities = new DesiredCapabilities();
	
	capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.6.4-beta");
	capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
	capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.2");
	capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6s");
	//capabilities.setCapability(MobileCapabilityType.UDID, "");
	
	//capabilities.setCapability(MobileCapabilityType.APP, "/Users/sjena/Desktop/Relay_Appium/ipa/SYW_Relay.app");
	capabilities.setCapability(MobileCapabilityType.APP, "settings");

	
	capabilities.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, "500000");
	capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
	driver = new IOSDriver<WebElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
	driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
	
}

**Comment by sjenasears** [comment] 2017-03-07 03:44
any solution?

**Comment by TikhomirovSergey** [comment] 2017-03-07 08:35
@sjenasears This is dependency conflict. Also I think that it is the duplicate of #588. I think now it should be  resolved. Could you read the mentioned issue.

**Comment by sjenasears** [comment] 2017-03-07 13:40
No it did not solve the error. I have included all jars for 5.0.0 Beta5

**Comment by TikhomirovSergey** [comment] 2017-03-23 08:17
@sjenasears 
Could you try it on 5.0.0-BETA6? Also could you check dependencies. I think that it is possible that your project may depend on some older Selenium version somehow.

**Closed** 2017-06-02 15:02 UTC
Labels: duplicate
