### ISSUE TITLE
pom.xml has multiple annotation errors

### ISSUE THREAD

**Issue by hsoehalim** [appium/java-client#322] opened 2016-02-23 00:53 UTC
Hi There,

Using eclipse, I was able to check out this project. But, I notice there's some issue with the pom.xml

Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (execution: default-testCompile, phase: test-
	 compile)
	- Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (execution: default-compile, phase: compile)

I think the issue was with "compilerId" within "configuration" properties. If I commented it out, it works.

```
...
...
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.3</version>
    <configuration>
        <source>1.7</source>
        <target>1.7</target>
        <compilerId>eclipse</compilerId>
    </configuration>
...
...
```

**Comment by TikhomirovSergey** [comment] 2016-02-23 12:33
Maybe it is the problem of Eclipse IDE or duplicate of #323

**Closed** 2016-02-23 12:33 UTC
Labels: duplicate
