### ISSUE TITLE
Unable to create Appium 2.0 Session Using AppiumDriverLocalService.

### ISSUE THREAD

**Issue by JYOTIPRAKASH225** [appium/java-client#2018] opened 2023-09-19 09:35 UTC
## Description

While creating Appium2.0 Session Programatically using AppiumDriverLocalService Getting NullPointerException

## Environment

* Java client build version or git revision if you use some snapshot: 8.5.0
* Appium server version or git revision if you use some snapshot: 2.1.3
* Desktop OS/version used to run Appium if necessary: MAC OS Ventura 13.4.1
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v20.6.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real

## Details

While creating Appium2.0 Session Programatically using AppiumDriverLocalService Getting NullPointerException

java.lang.NullPointerException
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:226)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at org.openqa.selenium.remote.service.DriverService$Builder.getLogOutput(DriverService.java:448)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:495)
	at io.appium.java_client.service.local.AppiumDriverLocalService.buildService(AppiumDriverLocalService.java:89)
	at com.appium.appium2Session.getDriver(appium2Session.java:42)
	at com.appium.appium2Session.main(appium2Session.java:29)

## Code To Reproduce Issue [ Good To Have ]

		service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder().withIPAddress("127.0.0.1")
				.usingPort(port).withAppiumJS(new File("/usr/local/lib/node_modules/appium/build/lib/main.js"))
				.withArgument(GeneralServerFlag.LOG_LEVEL, "debug"));
		DesiredCapabilities capabilities = new DesiredCapabilities();

		capabilities.setCapability("platformName", "iOS");
		capabilities.setCapability("appium:platformVersion", "15");
		capabilities.setCapability("appium:deviceName", "jyotipraksh's iPhone");
		capabilities.setCapability("appium:automationName", "XCUITest");
		capabilities.setCapability("appium:app", bundleID);
		capabilities.setCapability("appium:udid", "6279765bfc1744548bec50ddc00780049a3f155c");
		capabilities.setCapability("appium:includeSafariInWebviews", true);
		capabilities.setCapability("appium:newCommandTimeout", 3600);
		capabilities.setCapability("appium:connectHardwareKeyboard", true);

		System.out.println("Appium context set to application :" + appName);
		driver = new IOSDriver(service, capabilities);

## Exception Stacktraces
(https://gist.github.com/JYOTIPRAKASH225/57d639519e62744800df3ef68300b915)

## Link To Appium Logs
java.lang.NullPointerException
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:226)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at org.openqa.selenium.remote.service.DriverService$Builder.getLogOutput(DriverService.java:448)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:495)
	at io.appium.java_client.service.local.AppiumDriverLocalService.buildService(AppiumDriverLocalService.java:89)
	at com.appium.appium2Session.getDriver(appium2Session.java:42)
	at com.appium.appium2Session.main(appium2Session.java:29)

**Comment by ashwithpoojary98** [comment] 2023-09-19 09:45
#2014 https://github.com/appium/java-client/issues/2014
Please refer to this bug. The issue with the log file.

**Comment by valfirst** [comment] 2023-09-20 09:06
Duplicate of #2004

**Closed by valfirst** 2023-09-20 09:06 UTC
