### ISSUE TITLE
cannot be cast to class io.appium.java_client.android.AndroidDriver (net.bytebuddy.renamed.java.lang.Object$ByteBuddy$8cPvc5VQ is in unnamed module of loader net.bytebuddy.dynamic.loading.ByteArrayClassLoader @18f55704; io.appium.java_client.android.AndroidDriver is in unnamed module of loader 'app'

### ISSUE THREAD

**Issue by Rabindra184** [appium/java-client#1707] opened 2022-06-04 09:53 UTC
## Description

I'm trying to use the decorator mechanism provided by selenium 4.
But following the doc to decorate the android driver, I get the exception

AndroidDriver:  on android (3ce90b0b-4d97-4cbd-8db7-c2aff01de9da).....driver1.....
java.lang.ClassCastException: class net.bytebuddy.renamed.java.lang.Object$ByteBuddy$8cPvc5VQ cannot be cast to class io.appium.java_client.android.AndroidDriver (net.bytebuddy.renamed.java.lang.Object$ByteBuddy$8cPvc5VQ is in unnamed module of loader net.bytebuddy.dynamic.loading.ByteArrayClassLoader @18f55704; io.appium.java_client.android.AndroidDriver is in unnamed module of loader 'app')
	at managers.WebDriverManager.androidDriver(WebDriverManager.java:199)

## Environment

Java client build version or git revision if you use some snapshot: 8.1.0
Appium server version or git revision if you use some snapshot: 1.22.3
Desktop OS/version used to run Appium if necessary: Mac Monterey
Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: node js
Mobile platform/version under test: android
Real device or emulator/simulator: Both

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]
AndroidDriver driver1 = new AndroidDriver(serviceUrl, capabilities);
        Log.info(driver1+".....driver1.....");
        try {
            driver = (AndroidDriver) new EventFiringDecorator(listener).decorate(driver1);
        }
        catch(Exception e){
            e.printStackTrace();
        }

## Exception Stacktraces

AndroidDriver:  on android (3ce90b0b-4d97-4cbd-8db7-c2aff01de9da).....driver1.....
java.lang.ClassCastException: class net.bytebuddy.renamed.java.lang.Object$ByteBuddy$8cPvc5VQ cannot be cast to class io.appium.java_client.android.AndroidDriver (net.bytebuddy.renamed.java.lang.Object$ByteBuddy$8cPvc5VQ is in unnamed module of loader net.bytebuddy.dynamic.loading.ByteArrayClassLoader @18f55704; io.appium.java_client.android.AndroidDriver is in unnamed module of loader 'app')

**Comment by mykola-mokhnach** [comment] 2022-06-04 10:23
Please provide the full stack trace

**Comment by mykola-mokhnach** [comment] 2022-06-04 10:27
Also I'm not quite sure one can case like `driver = (AndroidDriver) new EventFiringDecorator(listener).decorate(driver1);`. EventFiringDecorator is not a subclass of AndroidDriver

**Comment by Rabindra184** [comment] 2022-06-04 17:33
WebDriver original = new AndroidDriver(); 
// it is expected that MyListener class implements WebDriverListener
// interface or its descendant
WebDriverListener listener = new MyListener(); 
WebDriver decorated = new EventFiringDecorator(listener).decorate(original);

**Comment by valfirst** [comment] 2022-06-06 08:57
Duplicate of #1694

**Closed** 2022-06-06 08:57 UTC

**Comment by iKabi** [comment] 2022-06-22 16:09
@valfirst any updates on this merge request?

**Comment by valfirst** [comment] 2022-06-23 07:07
@iKabi which request do you mean?

**Comment by iKabi** [comment] 2022-06-23 10:35
> @iKabi which request do you mean?

@valfirst open PR#17037 I hope that is to fix this class cast exception?

**Comment by valfirst** [comment] 2022-06-23 11:17
I guess you mean PR to https://github.com/SeleniumHQ/selenium/, so it's better to ask for its status in the corresponding repository
