### ISSUE TITLE
Exception is thrown when using TouchAction().longPress() more than once.

### ISSUE THREAD

**Issue by BrantK** [appium/java-client#365] opened 2016-04-22 00:00 UTC
## Description

Exception is thrown when using TouchAction().longPress() more than once. Doesn't occur when just using TouchAction().press(). Logs didn't really provide any information. I see there's a note about TouchAction being fixed but didn't see an issue for the longPress. 
## Environment
- java client revision: b511c35f7a38bbc7951b322281508f782078e9f6
- Appium v1.5.1
- Node.js v4.2.6
- Android 6.0.1 device
- Real device
## Code To Reproduce Issue

Repro:

```
TouchAction action = new TouchAction(driver);
        try {
            action.longPress(0, 0).release().perform();
            action.longPress(0, 0).release().perform();
        } catch (Exception e) {
            e.printStackTrace();
        }
```
## Exception stacktraces

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)

**Comment by BrantK** [comment] 2016-04-22 00:32
So after further testing, it looks like the problem is with waitAction which I'm assuming longPress uses.

**Comment by TikhomirovSergey** [comment] 2016-04-27 08:11
@BrantK 
Have you tried to update Appium server?
https://github.com/appium/appium/releases/tag/v1.5.2

Also, I can't reproduce this issue.
Can you attach server output?

**Comment by BrantK** [comment] 2016-04-27 19:28
Here's the server output:

https://gist.github.com/BrantK/2f1992d1842eb6e4b89c2674b239889a

**Comment by SrinivasanTarget** [comment] 2016-04-28 15:46
@BrantK Thanks for sharing logs.I'm not able to reproduce the same in Appium 1.5.2 with the above/similar code snippet.Would be helpful if you provide the code snippet you have used as well here.

**Comment by BrantK** [comment] 2016-04-28 19:08
@SrinivasanTarget here is a code example that gives me the exception:
https://gist.github.com/BrantK/31a6a80a30135de5c3668c70fc0964b1

Also here is the full error that's shown:
https://gist.github.com/BrantK/6e0ee0401628849871f106389a67cbf2

**Comment by SrinivasanTarget** [comment] 2016-04-28 19:35
Cool Thanks @BrantK. Didn't notice it's an issue on Android. Sorry have tried on iOS.Will get back on android soon.

**Comment by SrinivasanTarget** [comment] 2018-09-14 07:51
Actions API is way forward on this. Closing this.

**Closed by SrinivasanTarget** 2018-09-14 07:51 UTC
Labels: Android, Needs investigation
