### ISSUE TITLE
Unable to switch WEBVIEW after upgrading Appium to v2.0.0-beta.46 and 47 - Android

### ISSUE THREAD

**Issue by baskarkarthik** [appium/java-client#1822] opened 2022-12-14 15:08 UTC
## Description

After upgrading Appium to v2.0.0-beta.46 unable to switch webview from native view from Native app
Same code working fine in Appium v1.22.3

Steps:
Run the below code in a native app contains webview
Switch from Native view to Web view

Expected: Should allow to switch without any issue
Actual: getting below error

> Got response with status 500: {"value":{"error":"disconnected","message":"disconnected: unable to connect to renderer\n (failed to check if window was closed: disconnected: unable to connect to renderer

## Environment

* Java client build version: v8.1.1, v8.3.0(Latest)
* Appium server version: v2.0.0-beta.46, v2.0.0-beta.47(Latest)
* Desktop OS/version used to run Appium if necessary: macOS Monterey v12.6
* Node.js version (unless using Appium.app|exe) :  node v18.7.0
* Mobile platform/version under test: Android Pixel 6(v13), Samsung S10 lite(v12)
* Real device or emulator/simulator: Real device

## Details
Mobile app browser: chrome v108.0.5359.79
chromedriver : v108.0.5359.71

## Code To Reproduce Issue [ Good To Have ]
```
//Driver details
capability.setCapability("device", aDevice);
capability.setCapability("newCommandTimeout", 100000);
capability.setCapability("platformName", platform);
capability.setCapability("udid", aUdid);
capability.setCapability("appPackage", appPkg); 
capability.setCapability("appActivity", appAct);
capability.setCapability("automationName", "UiAutomator2");
capability.setCapability("setWebContentsDebuggingEnabled", true);

AppiumDriver driver = new AndroidDriver(new URL(serverUrl), capability);

Set<String> contexts = ((SupportsContextSwitching) driver()).getContextHandles();
        System.out.println("CONTEXT="+contexts);  //prints CONTEXT=[NATIVE_APP, WEBVIEW_chrome]
         for (String context : contexts) {
             if (context.contains("WEBVIEW")) {
                 ((SupportsContextSwitching) driver()).context(context);
                 break;
             }
         }
```

## Exception Stacktraces
https://gist.github.com/baskarkarthik/88fa2d786249cc850ea0bfd725cc18f3

## Link To Appium Logs
https://gist.github.com/baskarkarthik/680356f09ae3d85064b7d17cee1afc66

**Comment by valfirst** [comment] 2022-12-23 13:33
Duplicate of https://github.com/appium/appium/issues/17934

**Closed by valfirst** 2022-12-23 13:33 UTC
