### ISSUE TITLE
Exception in thread "main" java.lang.AbstractMethodError: Receiver class...

### ISSUE THREAD

**Issue by RYenike** [appium/java-client#2010] opened 2023-09-11 11:58 UTC
## Description

Exception in thread "main" java.lang.AbstractMethodError: Receiver class io.appium.java_client.service.local.AppiumServiceBuilder does not define or inherit an implementation of the resolved method 'abstract void loadSystemProperties()' of abstract class org.openqa.selenium.remote.service.DriverService$Builder.

## Environment

* Appium server version (output of appium --version):2.1.3
Appium driver(s) and their version(s): UiAutomator2@2.29.2
Node.js version (output of node --version): 18.17.1
npm version (output of npm --version):9.8.1
java version - 11.0
java_client - 8.5.1
Selenium - 4.12.1

## Code To Reproduce Issue [ Good To Have ]

AppiumServiceBuilder builder = new AppiumServiceBuilder();

        builder

                .withAppiumJS(new File("C:\\Users\\hkakarla\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js"))

                .usingDriverExecutable(new File("C:\\Program Files\\nodejs\\node.exe"))

                .usingPort(4725)
// .withArgument(GeneralServerFlag.LOCAL_TIMEZONE)

// .withLogFile(new File("Appiumlog.txt"))

                .withIPAddress("127.0.0.1");

        server = AppiumDriverLocalService.buildService(builder);
           server.start()

## Exception Stacktraces

Please create a [gist](https://gist.github.com) with the pasted stacktrace of the exception thrown by java.

## Link To Appium Logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by ashwithpoojary98** [comment] 2023-09-18 14:56
@RYenike add Appium logs

**Comment by valfirst** [comment] 2023-09-20 09:08
Duplicate of #1907

**Closed by valfirst** 2023-09-20 09:08 UTC
