### ISSUE TITLE
findDefaultExecutable executing login shell

### ISSUE THREAD

**Issue by peter-sgouros** [appium/java-client#868] opened 2018-04-12 21:39 UTC
## Description

running on a system where the environment NODE_BINARY_PATH is not set (or you are running a test inside Eclipse where the local variables are not picked up,) the AppiumServiceBuilder attempts to find the node installation by executing a shell script and parsing the output.

on a Mac at least, the execution of the shell script returns not only the script output, but also the 'welcome' message (or any text) generated by the local .bashrc file. which in my case prints out several lines of text after parsing the /etc/hosts file. a simple way to synthesize this is to add the line `cat /etc/hosts` to the .bashrc file somewhere. or perhaps `echo "some text to confuse Appium with"`

this, as you might expect, causes the 'filePath' variable to contain a lot of junk, and of course the parsing for the filename fails.

Mac OS, 10.12.6
Eclipse, oxygen

in this case, Eclipse does not pick up the system's environment variables, so it was perpetually bypassing the direct request for the node binary. 

it is in this method:
`    private File findNodeInCurrentFileSystem() {
        setUpNPMScript();

        String instancePath;
        CommandLine commandLine;
        try {
            if (Platform.getCurrent().is(Platform.WINDOWS)) {
                commandLine = new CommandLine(CMD_EXE, "/C", "npm root -g");
            } else {
                commandLine = new CommandLine(BASH, "-l", npmScript.getAbsolutePath());
            }
            commandLine.execute();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
       /*this fails because the return value from scraping the terminal response contained in 'commandLine', contains quite a lot of extra text beyond the expected filename output */
        instancePath = (commandLine.getStdOut()).trim();
        try {
            File defaultAppiumNode;
            if (StringUtils.isBlank(instancePath) || !(defaultAppiumNode =
                new File(instancePath + File.separator
                    + APPIUM_FOLDER)).exists()) {
                String errorOutput = commandLine.getStdOut();
                throw new InvalidServerInstanceException(ERROR_NODE_NOT_FOUND,
                    new IOException(errorOutput));
            }
            //appium servers v1.5.x and higher
            File result;
            if ((result = new File(defaultAppiumNode, APPIUM_NODE_MASK)).exists()) {
                return result;
            }

            throw new InvalidServerInstanceException(ERROR_NODE_NOT_FOUND, new IOException(
                "Could not find a file " + APPIUM_NODE_MASK
                    + " in the "
                    + defaultAppiumNode + " directory"));
        } finally {
            commandLine.destroy();
        }
    }
`

**Comment by SrinivasanTarget** [comment] 2018-05-26 06:51
duplicate of https://github.com/appium/java-client/issues/761

**Closed** 2018-06-06 15:13 UTC
Labels: User side problem/problem of an external tool
