### ISSUE TITLE
driver.lockScreen() not working as expected.

### ISSUE THREAD

**Issue by namannigam** [appium/java-client#315] opened 2016-02-07 04:43 UTC
Quoting from [SO-35223434](http://stackoverflow.com/questions/35223434/does-driver-lockscreen-method-works)-
We have called `driver.lockScreen(20);` in my test followed by `Runtime.getRuntime().exec("adb shell input keyevent 26");` to unlock screen. But the problem is the device is not getting locked for 20 sec. The next statement keyevent 26 is unlocking the device as soon as device is locked. So why we are providing `20 sec` parameter?
Looking further into this, the AppiumDriver.java has this to say : 
`/**
     * Lock the device (bring it to the lock screen) for a given number of
     * seconds
     *
     * @param seconds
     *            number of seconds to lock the screen for
     */
    public void lockScreen(int seconds) {
        execute(LOCK, ImmutableMap.of("seconds", seconds));
    }`

**Comment by TikhomirovSergey** [comment] 2016-02-07 12:45
I will try to reproduce. But it can be the server-side problem.

**Comment by TikhomirovSergey** [comment] 2016-02-07 15:47
It is the server side problem. 
https://github.com/appium/appium/issues/6077

**Comment by namannigam** [comment] 2016-02-07 18:55
@TikhomirovSergey there's definitely some issue with the `lockScreen()` but just to clear the [appium/appium#6077](https://github.com/appium/appium/issues/6077) depicts that the screen remains locked. While in our case the screen does not remain lock for the specified sleep time.

**Comment by TikhomirovSergey** [comment] 2016-02-07 20:31
>While in our case the screen does not remain lock for the specified sleep time.
I'm searching for the cause of this problem. It is already reported probably.

**Comment by imurchie** [comment] 2016-02-08 23:47
The server is currently not implementing the right thing. For Android it just locks and returns. This is a bug and will be fixed.

**Comment by imurchie** [comment] 2016-02-09 18:07
Talking this over, this appears to be the desired behavior. The locking-waiting-unlocking is necessary for iOS, where it is the only way to do any locking. For Android it should just lock. If you want it to unlock, you can call unlock.

I am making the seconds parameter optional, and documenting this difference.

**Closed** 2016-02-12 07:56 UTC
Labels: refactor
