### ISSUE TITLE
Error parsing session info from SauceLabs

### ISSUE THREAD

**Issue by itaibh** [appium/java-client#1608] opened 2021-12-08 07:44 UTC
## Description

When I run the attached code with Appium version 8.0.0-beta on SauceLabs, in the SauceLabs dashboard I see the test running, I see the device launching and the app starting, so I know the session had started. But then the client fails with this error:

```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response
```

See full exception log here: https://gist.github.com/itaibh/5cdf5eb606de58299aed0abb4005c0e0

## Environment

I give here sample code that uses the following capabilities:
* IOS 13.0 Simulator
* Appium 1.17.1

However, the same issue occurs on other configurations, where the common thing is that I use Appium Java Client 8.0.0-beta and SauceLabs. Notice this doesn't happen on BrowserStack (which is the only other provider I tested on).

## Code To Reproduce Issue

```
import io.appium.java_client.AppiumDriver;
import org.openqa.selenium.MutableCapabilities;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.Test;
import java.net.URL;

public class TestAppiumOnSauceLabs {
    @Test
    public void TestOnSauce() {
        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability("browserName", "");
        caps.setCapability("name", "iOS Native Demo");
        caps.setCapability("platformName", "iOS");
        caps.setCapability("appium:platformVersion", "13.0");
        caps.setCapability("appiumVersion", "1.17.1");
        caps.setCapability("appium:deviceName", "iPhone XS Simulator");

        MutableCapabilities sauceOpts = new MutableCapabilities();
        sauceOpts.setCapability("username", System.getenv("SAUCE_USERNAME"));
        sauceOpts.setCapability("accessKey", System.getenv("SAUCE_ACCESS_KEY"));
        caps.setCapability("sauce:options", sauceOpts);

        caps.setCapability("app", "https://applitools.jfrog.io/artifactory/Examples/eyes-ios-hello-world/1.2/eyes-ios-hello-world.zip");

        WebDriver driver = null;
        try {
            driver = new AppiumDriver(new URL("https://ondemand.saucelabs.com:443/wd/hub"), caps);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (driver != null) {
                driver.quit();
            }
        }
    }
}

```

## Link To Appium Logs

https://gist.github.com/itaibh/d85b1a33257fa5101816f1214a48fda9

**Comment by mykola-mokhnach** [comment] 2021-12-08 07:48
I don't think your issue has anything to do with java client. Please report it to Sauce customer support.

**Comment by itaibh** [comment] 2021-12-08 07:54
@mykola-mokhnach The problem is with the parsing of the response. I can't tell what the response is, but from SauceLabs logs it seems to be a valid JSON, so that's why I think this IS a client issue. However, if it's not, then for such a simple test code running on such a known vendor I would think you'll have much more impact solving this with SauceLabs than I would.

**Comment by mykola-mokhnach** [comment] 2021-12-08 07:58
I assume there is some problem while the client fetches the response from their infra. Basically, the error mean then java client was expecting to get a valid JSON as a response to createSession call, but got nothing instead. Also, in Appium logs we can see that the correct response has been generated. So the issue must happen somewhere in between the Appium server and the client lib.

**Comment by itaibh** [comment] 2021-12-08 08:10
I'll try to reproduce this with C# (Appium 5.0.0-beta01). If it happens there too then the issue is most likely at SauceLabs side, but if not then it means the issue is most likely in the Java client side.
In any way, what I wrote about who's having more impact stands, so if we come to a conclusion this is something on SauceLabs side I take it as this is the Appium project responsibility to approach SauceLabs. You can then place the link to the issue or whatever here so I can comment on it or thumb up.

**Comment by valfirst** [comment] 2021-12-08 08:12
The root cause is SauceLabs returns HTTP `303` with headers like 
```
{
  date=[Wed, 08 Dec 2021 08:08:51 GMT],
  server=[monocle/0.42],
  content-length=[0],
  content-type=[text/html],
  location=[/wd/hub/session/XXXXXXXX-retracted-XXXXXXX]
}
```

Default Selenium HTTP client doesn't follow redirects. I'm not sure whether it should be fixed on SauceLabs side, or Selenium client side, or Appium client side.

**Comment by valfirst** [comment] 2021-12-08 08:15
BTW changing HTTP client to follow redirects fixes the issue.

**Comment by mykola-mokhnach** [comment] 2021-12-08 08:22
> The root cause is SauceLabs returns HTTP 303 with headers like

This makes sense if it is necessary to wait longer and to avoid connection timeout. @valfirst Do you know how to enable redirects by default for the Selenium's HTTP client.

**Comment by itaibh** [comment] 2021-12-08 08:25
> I'll try to reproduce this with C# (Appium 5.0.0-beta01). 

It works in C#, meaning it's a java client issue.

**Comment by itaibh** [comment] 2021-12-08 08:30
> BTW changing HTTP client to follow redirects fixes the issue.

@valfirst How can I do that?

**Comment by mykola-mokhnach** [comment] 2021-12-08 08:42
AFAIK HTTP client creation options are [hardcoded](https://github.com/SeleniumHQ/selenium/blob/cbb2796d653a7c552e5c8d7f72ff59425ec373d7/java/src/org/openqa/selenium/remote/http/netty/NettyClient.java#L81) inside Selenium lib and I don't see any simple way to change these. Perhaps we could only add an ugly hack to https://github.com/appium/java-client/blob/158615250499b5a3c251a38928c7d4771d3f281e/src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java#L149 (e.g. check if the actual response code == 302 and then try to reload the url)

**Comment by valfirst** [comment] 2021-12-08 08:45
for now there is no way to enable following redirects in Selenium HTTP client, I've checked my assumption via debug: just changed the client

**Comment by mykola-mokhnach** [comment] 2021-12-08 08:45
Linked the original Selenium's bug. Not sure if it is going to be solved soon though

**Comment by mykola-mokhnach** [comment] 2021-12-08 10:44
Selenium lib got a patch there. We'd have to patch its version for java-client as soon as it reaches release state and push a new beta

**Comment by mykola-mokhnach** [comment] 2021-12-08 11:25
@KazuCocoa Could you please confirm that both HTTP clients in Ruby and Python have redirects handling enabled by default?

**Comment by KazuCocoa** [comment] 2021-12-08 17:32
Ruby appium client refers to selenium's one. It has https://github.com/SeleniumHQ/selenium/blob/9d9e4c7185cd44aafb18e707a34bcfc851fa9a31/rb/lib/selenium/webdriver/remote/http/default.rb#L104-L109 so Ruby should be ok.
Let me check python soon

**Comment by KazuCocoa** [comment] 2021-12-08 18:17
Python client handles connections via `urllib3`. It sets redirect stuff True by default, so I think python is also ok.

**Comment by madhusudhan-patha** [comment] 2021-12-14 15:36
I have come across this issue with Serenity BDD (3.1.1) which has Appium java-client: 8.0.0-beta. Here are some observations.

1. IOS tests are throwing the error, when executed using SauceLabs, as shown in description ( 303 status code, followed by unable to parse the json response). Reported a ticket https://github.com/serenity-bdd/serenity-core/issues/2634. 
2. But, Android test scripts got executed with Saucelabs  with the same java client version and serenity BDD. It is not giving any redirect status codes or json parsing errors

**Closed** 2021-12-18 21:28 UTC
Labels: InProgress
