### ISSUE TITLE
WebDriverException: Returned value cannot be converted to WebElement

### ISSUE THREAD

**Issue by apanashchenko** [appium/java-client#727] opened 2017-09-15 13:00 UTC
## Description

Hi guys!
I tried to update the java-client version from 5.0.0-BETA9 to 5.0.3 and have error:

Caused by: WebDriverException: Returned value cannot be converted to WebElement: {ELEMENT=5B07CB4B-816B-49B9-9101-9437E16B094F, label=, type=XCUIElementTypeTextField}

## Environment

* java client build 5.0.3.
* Appium server: 1.6.5
* Desktop OS: MacOS
* Node.js version: v8.4.0
* Mobile platform: iOS v10.3.3
* Real device: iphone 7

## Details

My pom.xml dependencies: 
https://gist.github.com/apanashchenko/9139209698b0c1655f9114a3a868dab3

When I tried to exclude selenium but have same issue.
https://gist.github.com/apanashchenko/5fffd6d00b4b8b22f2464d1da8a8857c

**Comment by TikhomirovSergey** [comment] 2017-09-16 07:29
@apanashchenko 
Could please you show some code sample to reproduce it and please show there the java stacktrace

**Comment by apanashchenko** [comment] 2017-09-17 13:07
@TikhomirovSergey 
You can create maven project and use all my dependency. 
This is java exception:
Caused by: WebDriverException: Returned value cannot be converted to WebElement: {ELEMENT=5B07CB4B-816B-49B9-9101-9437E16B094F, label=, type=XCUIElementTypeTextField

**Comment by TikhomirovSergey** [comment] 2017-09-19 12:02
@apanashchenko 
This string is looking suspiciously
https://gist.github.com/apanashchenko/9139209698b0c1655f9114a3a868dab3#file-pom-xml-L15

and this too
https://gist.github.com/apanashchenko/5fffd6d00b4b8b22f2464d1da8a8857c#file-pom_exclude-xml-L15

Selenide still depends on older selenium version
https://mvnrepository.com/artifact/com.codeborne/selenide/4.6

And there is dependency conflict. Please exclude selenium from selenide and try. I am labeling this issue as invalid.

**Comment by TikhomirovSergey** [comment] 2017-09-20 15:46
@apanashchenko I am closing this ticket. If you are not agree and you are still facing up this issue then please reopen this issue and provide some more details

**Closed by TikhomirovSergey** 2017-09-20 15:46 UTC
Labels: invalid

**Comment by ksurya28995** [comment] 2018-10-21 04:46
Hi Frnds,

I found the solution, but cant explain how it works. But it works for me as a miracle.

Just add the below line, and magic happens. I dont have any idea how that makes it work..HAHAHA..

capability.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "60");
