### ISSUE TITLE
Widget class cannot be in Groovy

### ISSUE THREAD

**Issue by aznime** [appium/java-client#340] opened 2016-03-15 06:24 UTC
## Description

When creating a widget, code must be in Java. An illegal access exception is thrown if it is coded in Groovy.

## Environment

* java client build version or git revision if you use some shapshot: **3.3.0**
* Appium server version or git revision you is use some shapshot: **1.14.16**
* Desktop OS/version used to run Appium if necessary: **OSX El Capitan (10.11.1)**
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: **0.12.7**
* Mobile platform/version under test: **iOS 9.2**
* Real device or emulator/simulator: **Simulator**

## Exception stacktraces

https://gist.github.com/aznime/54263754d2a312ffb1bc

**Comment by TikhomirovSergey** [comment] 2016-03-15 07:02
@aznime 
Could you share a gist with code of this class?
_com.jumbo.shared.widgets.PlayWidget_

It looks like a bug but I don't know how to reproduce it. Java client widget tests use objects with protected constructors and everything is ok.

**Comment by TikhomirovSergey** [comment] 2016-03-15 07:06
@aznime 
Also.
How should I check it? Have you a Groovy project?

**Comment by aznime** [comment] 2016-03-16 04:01
Sorry for the late reply. I was trying to create a demo project for this purpose.

You can find it here: https://github.com/aznime/jumbo-mobile-tests

**Comment by TikhomirovSergey** [comment] 2016-03-16 08:05
@aznime 
Thank you. I've started to search for the root cause of the error.

**Comment by TikhomirovSergey** [comment] 2016-03-17 08:59
@aznime 
Ok. It seems I know the root cause. I think that cglib and reflection are not used properly at some cases and I'm going to fix it. 

As a workaround I can advice you to change class modifiers to public. 

```java
public class UICatalogWidget extends Widget {
...
}
```

Can you do it and send a message about the result.

**Comment by aznime** [comment] 2016-03-18 05:07
@TikhomirovSergey 
I got the same exception after explicitly using the public modifier.

**Comment by TikhomirovSergey** [comment] 2016-03-23 17:32
@aznime 
It needs for some redesign. It is going to be included at 3.4.1

**Comment by TikhomirovSergey** [comment] 2016-03-23 18:33
@aznime 
The fix is going to be included at 3.4.1 very soon!

**Comment by TikhomirovSergey** [comment] 2016-03-27 19:02
The fix has been merged and it is going to be published

**Closed by TikhomirovSergey** 2016-03-27 19:02 UTC
Labels: bug
