### ISSUE TITLE
Appium Press, WaitAction, MoveTo is slow on Android

### ISSUE THREAD

**Issue by seanLiu716** [appium/java-client#1322] opened 2020-03-29 15:45 UTC
## Description
I try to run a series press, wait, moveto, wait, moveto, release, perform actions.
the wait time is about 50-100ms each.

It runs perfect on ios. but on Android, the wait time is over 1 second for a supposed 100ms. Not sure what is the root cause.

My sample code: omit a few moveto, waitAction

TouchAction action = new TouchAction(androidDriver);
action.press(point(100,100)).waitAction(WaitOptions.waitOptions(Duration.ofMills(100))).moveTo(point(100,200)).waitAction(WaitOptions.waitOptions(Duration.ofMills(100))).moveTo(point(200,300))
.release().perform();

## Environment

* Java client build version : V7.0.0,  selenium-java: 3.141.59
* Appium server version: V1.15.1
* Desktop OS/version: Windows 10
* Mobile platform/version under test: Android 9.0
* Real device or emulator/simulator: Moto G6, real device

## Details

Please provide more details, if necessary.

## Link To Appium Logs

[log.txt](https://github.com/appium/java-client/files/4399168/log.txt)

**Comment by mykola-mokhnach** [comment] 2020-03-29 15:48
Possible duplicate of https://github.com/appium/appium/issues/12707

**Comment by seanLiu716** [comment] 2020-03-29 16:21
Thanks Mykola for the reply.

I tried set trackScrollEvents to false. The issue still exists.

 I am not sure the issue is related to my particular app (pokemon go) in my case, or it is widely appliable, just people do not need fast reaction. 

Hand touch on the phone works fast.
The code works smoothly on iPhone.

**Comment by cheffey** [comment] 2020-03-31 13:10
> Thanks Mykola for the reply.
> 
> I tried set trackScrollEvents to false. The issue still exists.
> 
> I am not sure the issue is related to my particular app (pokemon go) in my case, or it is widely appliable, just people do not need fast reaction.
> 
> Hand touch on the phone works fast.
> The code works smoothly on iPhone.

There are 3 different swiping in android, because appium call different api combo in uiautomator2:
press moveTo release
press wait moveTo release
longPress moveTo release
Even though command looks alike, but they works differently.
also try press(A) moveTo(B) moveTo(C) release, A B C are in the same line with distances > 20, in my scenario it works out to be move B to C. Find out which one works for you. Have Fun!

**Comment by mykola-mokhnach** [comment] 2020-03-31 14:42
You could also try W3C actions. There is no tracking. See https://appiumpro.com/editions/29 for example

**Comment by seanLiu716** [comment] 2020-03-31 20:10
Thanks mykola. I tried that, slow too. 

> You could also try W3C actions. There is no tracking. See https://appiumpro.com/editions/29 for example

**Comment by seanLiu716** [comment] 2020-03-31 20:14
Thanks Cheffey. I need to control the wait time or speed accurately. That is why I chose
press wait moveTo wait moveTo release

For the other two options, if time can not be controlled, I can not use them.


> > Thanks Mykola for the reply.
> > I tried set trackScrollEvents to false. The issue still exists.
> > I am not sure the issue is related to my particular app (pokemon go) in my case, or it is widely appliable, just people do not need fast reaction.
> > Hand touch on the phone works fast.
> > The code works smoothly on iPhone.
> 
> There are 3 different swiping in android, because appium call different api combo in uiautomator2:
> press moveTo release
> press wait moveTo release
> longPress moveTo release
> Even though command looks alike, but they works differently.
> also try press(A) moveTo(B) moveTo(C) release, A B C are in the same line with distances 
> 20, in my scenario it works out to be move B to C. Find out which one works for you. Have Fun!

**Comment by cheffey** [comment] 2020-04-01 00:49
You can put wait option in longpress(longpressOption)

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=chefxie&uid=chefxie%40chancetop.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Achefxie%40chancetop.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
chefxie
邮箱：chefxie@chancetop.com

签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制

On 04/01/2020 04:14, seanLiu716<mailto:notifications@github.com> wrote:

Thanks Cheffey. I need to control the wait time or speed accurately. That is why I chose
press wait moveTo wait moveTo release

For the other two options, if time can not be controlled, I can not use them.

Thanks Mykola for the reply.
I tried set trackScrollEvents to false. The issue still exists.
I am not sure the issue is related to my particular app (pokemon go) in my case, or it is widely appliable, just people do not need fast reaction.
Hand touch on the phone works fast.
The code works smoothly on iPhone.

There are 3 different swiping in android, because appium call different api combo in uiautomator2:
press moveTo release
press wait moveTo release
longPress moveTo release
Even though command looks alike, but they works differently.
also try press(A) moveTo(B) moveTo(C) release, A B C are in the same line with distances
20, in my scenario it works out to be move B to C. Find out which one works for you. Have Fun!

**Comment by mykola-mokhnach** [comment] 2020-04-01 16:38
@seanLiu716 Please install appium@beta and try W3C actions again. Please also share the logcat output if the performance is not good this time.

**Comment by seanLiu716** [comment] 2020-04-02 02:16
@mykola-mokhnach 
I update to Appium 1.17.0. The beta version installation 
npm i appium@1.17.1-beta.0
has issue for some reason.

With that, the W3C actions took 3409 ms. Should be less than 1 sec. 
The press, wait, moveTo took over 9 seconds.

The log file can be found here
https://gist.github.com/seanLiu716/ebbbea87410878a1b8c4665809f3559b

Please advise how to speed up to make it close to real time. Thanks.

**Comment by cheffey** [comment] 2020-04-02 05:26
May I ask why you wanna need to control the time? To control the acceleration after swipe?

**Comment by mykola-mokhnach** [comment] 2020-04-02 06:21
simply do `npm install -g appium@beta`

I need then the logcat output, not the server log

**Comment by seanLiu716** [comment] 2020-04-02 13:00
> May I ask why you wanna need to control the time? To control the acceleration after swipe?

For some games, the movement/acceleration needs to be precisely controlled.

**Comment by seanLiu716** [comment] 2020-04-02 13:04
> simply do `npm install -g appium@beta`
> 
> I need then the logcat output, not the server log

Tried the v1.17.1-beta.0, the timing is hugely improved:
press-wait-moveTo: >9 sec
W3C actions in V1.17: >3 sec
W3C actions in v1.17.1-beta.0: ~ 1 sec

Could you provide insight what caused the issue? How did it get fixed?

Thanks.

Also where can I find the logcat log file?

**Comment by mykola-mokhnach** [comment] 2020-04-02 13:11
Check https://github.com/appium/appium-uiautomator2-server/pull/339 for more technical details.

More info on logcat could be found in https://appiumpro.com/editions/53

**Closed by mykola-mokhnach** 2020-04-02 13:11 UTC
