### ISSUE TITLE
Problem initializing driver for Appium 8.1 - Platform$22 cannot be cast to class java.lang.String

### ISSUE THREAD

**Issue by Jakwado** [appium/java-client#1703] opened 2022-06-01 09:43 UTC
## Description

I have problem initializing Appium webDriver after migration to 8.1. Solutions provided in [this ticket](https://discuss.appium.io/t/unable-to-initialize-driver-using-appium-java-8/36038) did not help me. Any support would be appreciated.

## Environment

* Java 15
* Appium 8.1
* Android 11
* Emulator Pixel 4 XL

## Details

My BaseOptions deserialize this json to map:

> 
> {
>   "platformName": "Android",
>   "platformVersion": "11",
>   "deviceName": "emulator-5554",
>   "appPackage": "be.aion.android.app.test",
>   "appActivity": "be.aion.android.app.initialization.ui.InitializationActivity",
>   "bundleId": "be.aion.android.app.test",
>   "sessionName": "Aion local",
>   "sessionDescription": "AionPl local test session",
>   "deviceOrientation": "portrait",
>   "noReset": true,
>   "fullReset": false,
>   "captureScreenshots": true,
>   "tagName": "",
>   "autoGrantPermissions": true,
>   "autoWebView": true,
>   "autoLaunch": false
> }
> 

Here is my pom:
> 
>     <properties>
>         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>         <maven.compiler.version>3.8.0</maven.compiler.version>
>         <spring.version>5.3.12</spring.version>
>         <appium.version>8.1.0</appium.version>
>         <selenium.version>4.2.0</selenium.version>
>         <junit.version>5.8.1</junit.version>
>         <lombok.version>1.18.22</lombok.version>
>         <assertj.version>3.21.0</assertj.version>
>         <awaitility.version>4.1.1</awaitility.version>
>         <reportportal.logger.version>5.1.1</reportportal.logger.version>
>         <reportportal.agent.version>5.1.1</reportportal.agent.version>
>         <feign.version>11.8</feign.version>
>     </properties>
> 
>     <dependencies>
>         
>         <dependency>
>             <groupId>io.appium</groupId>
>             <artifactId>java-client</artifactId>
>             <version>${appium.version}</version>
>         </dependency>
>         
>         <dependency>
>             <groupId>org.seleniumhq.selenium</groupId>
>             <artifactId>selenium-support</artifactId>
>             <version>${selenium.version}</version>
>         </dependency>
>         <dependency>
>             <groupId>org.seleniumhq.selenium</groupId>
>             <artifactId>selenium-java</artifactId>
>             <version>${selenium.version}</version>
>         </dependency>
> 
> 

## Code To Reproduce Issue [ Good To Have ]

The way I initialize driver:

> 
>     private AppiumDriver waitForDeviceAvailability() throws IOException {
>         BaseOptions capabilities = getDesiredCapabilities();
>         capabilities.setCapability("waitForIdleTimeout", 0L);
>         return await()
>                 .ignoreExceptionsInstanceOf(WebDriverException.class)
>                 .atMost(DRIVER_TIMEOUT)
>                 .pollInterval(DRIVER_INTERVAL)
>                 .until(
>                         () -> initializeDriver(capabilities),
>                         Objects::nonNull
>                 );
>     }
> 
>     /**
>      * Method initializing webDriver for proper platform defined in TestMetaInformation
>      */
>     private AppiumDriver initializeDriver(BaseOptions capabilities) {
>         log.info("Attempt to establish connection with device: {}", capabilities.getCapability(DEVICE_NAME));
>         try {
>             if (testMetaInformation.getPlatformType().equals(PlatformType.ANDROID)) {
>                 return new AndroidDriver(new URL(testMetaInformation.getUrl()), capabilities);
>             }
>             return new IOSDriver(new URL(testMetaInformation.getUrl()), capabilities);
>         } catch (Exception e) {
>             log.info("Problem establishing connection: \n{}", e.getMessage());
>             return null;
>         }
>     }
> 

## Exception Stacktraces

11:28:39.394 INFO  c.v.a.d.DriverBuilder - awaitility-thread: - Problem establishing connection: 
class org.openqa.selenium.Platform$22 cannot be cast to class java.lang.String (org.openqa.selenium.Platform$22 is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

**Comment by valfirst** [comment] 2022-06-01 09:57
Duplicate of #1701

**Closed by valfirst** 2022-06-01 09:57 UTC
